### ISSUE TITLE
Docs for env-vars are incorrect 

### ISSUE THREAD

**Issue by shubhaat** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#13]
We tried to use the documentation to run the acceptance tests locally. The documentation specifies setting the following environment variables

```
CF_DEPLOYMENT_NAME - name of the Cloud Foundry deployment to backup and restore
CF_API_URL - Cloud Foundry api url
CF_ADMIN_USERNAME - Cloud Foundry api admin user
CF_ADMIN_PASSWORD - Cloud Foundry api admin password
BOSH_ENVIRONMENT - URL of BOSH Director which has deployed the above Cloud Foundries
BOSH_CLIENT - BOSH Director username
BOSH_CLIENT_SECRET - BOSH Director password
BOSH_CERT_PATH - path to BOSH Director's CA cert
BBR_BUILD_PATH - path to BBR binary
DEFAULT_TIMEOUT_MINS - timeout for commands run in the test. Defaults to 15 minutes.
```

On running `./scripts/run_acceptance_tests_local.sh` we have encountered the following errors:

```
./scripts/run_acceptance_tests_local.sh: line 8: BOSH_CA_CERT: parameter null or not set
```

and 

```
./scripts/run_acceptance_tests_local.sh: line 9: BOSH_GW_HOST: parameter null or not set
```

BOSH_GW_HOST is not included in the documentation at all.

**Comment by shubhaat** [comment]
We found that all the following env vars are required and undocumented:

```
export BOSH_GW_HOST=35.188.221.176:25555
export BOSH_GW_USER=jumpbox
export BOSH_GW_PRIVATE_KEY_CONTENTS="REDACTED"
export SSH_DESTINATION_CIDR="10.0.0.0/8"
export NFS_SERVICE_NAME="sda "
export NFS_PLAN_NAME="sds "
export NFS_BROKER_USER="sda "
export NFS_BROKER_PASSWORD="sda "
export NFS_BROKER_URL="sda"
```

We have as of yet been unable to run this script successfully. We are currently getting this error:
```
$ ./scripts/run_acceptance_tests_local.sh
Starting SSH tunnel, you may be prompted for your OS password...
Running DRATs...
ssh: Could not resolve hostname https://35.188.221.176:25555: nodename nor servname provided, or not known
client: fatal: failed to establish ssh session (1)
./scripts/run_acceptance_tests.sh: line 23: dep: command not found
./scripts/run_acceptance_tests_local.sh: line 38: kill: (86169) - No such process
```

**Comment by shubhaat** [comment]
We did some more digging, and found the following issues 

1. The `BOSH_ENVIRONMENT` takes a scheme and a port, but  `BOSH_GW_HOST` takes an IP only 
2. `BOSH_CERT_PATH` has been renamed `BOSH_CA_CERT` 
3. We had trouble setting `BOSH_GW_PRIVATE_KEY_CONTENTS` and `BOSH_CERT_PATH` in a script. We got past an error using `export BOSH_GW_PRIVATE_KEY_CONTENTS="$(bbl ssh-key)"` and `export BOSH_CA_CERT="$(bbl director-ca-cert)"`

**Comment by shubhaat** [comment]
Now we're getting this error:

```
• Failure in Spec Setup (BeforeEach) [369.189 seconds]
backing up Cloud Foundry
/Users/sanjurtupil/go/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/acceptance_test.go:13
  backups and restores a cf [BeforeEach]
  /Users/sanjurtupil/go/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner/runner.go:45

  Expected error:
      <*os.PathError | 0xc420081c20>: {
          Op: "mkdir",
          Path: "cf-routing-cf-home",
          Err: 0x11,
      }
      mkdir cf-routing-cf-home: file exists
  not to have occurred
```

**Comment by henryaj** [comment]
Looks like the last test run left some state behind: https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/blob/master/runner/runner.go#L40

This is usually cleaned up in an AfterEach(), but that doesn't seem to have run - was the test process killed before it could clean up?

**Comment by edwardecook** [comment]
Hey we've updated our README to reflect recently added/changed environment variables, if the state not being cleaned up continues to be an issue it would probably make sense to open a separate issue for it.

Cheers
