### ISSUE TITLE
Update documentation to include setting release_level_backup to false for components backup and restore to be a no-op

### ISSUE THREAD

**Issue by shubhaat** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#15]
My tests took about 50 minutes to run, I set the`FOCUSED_SUITE_NAME=cf-routing` but did not set `release_level_backup` which means the backup and restore scripts for every component run. This makes a very long run for DRATs. It might be better to explicitly ask team to set `release_level_backup` to false for components you want to exclude. This would make the run much shorter.

**Comment by edwardecook** [comment]
@shubhaat we think it would be dangerous for people to turn off scripts from other releases, as there some dependencies between scripts. We realise the entire bbr backup & restore cycle takes a long time to run, but we think encouraging people to fiddle with the scripts deployed with cf in this way would lead to confusing errors which would be a distraction from the issues the DRATS tests are intended to drive out.

**Comment by edwardecook** [comment]
@shubhaat following the discussion on Friday and the comment above I think this issue can be closed, do feel free to re-open it if you think there is any further action needed.
