### ISSUE TITLE
Desire to run DRATS with an integration config

### ISSUE THREAD

**Issue by tophat8855** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#18]
Hi friends!

We are interested in running DRATS with an integration config instead of environment variables like [CATS](https://github.com/cloudfoundry/cf-acceptance-tests#test-configuration) and the other -ATS tests. Is this something you all are planning in your backlog? Would you like a pull request for this? It would be nice for all the -ATS tests to be set up the same way. 

Thanks from the Relint team!

**Comment by thereses** [comment]
Hi @tophat8855 great idea. We will make the change in a few weeks.

**Comment by tophat8855** [comment]
We went ahead and started working on a PR a few days ago. It's about done.

**Comment by tophat8855** [comment]
PR was merged.
