### ISSUE TITLE
ci/drats-with-integration-config/task.yml  does not expose `DEFAULT_TIMEOUT_MINS`, `FOCUSED_SUITE_NAME`, and `SKIP_SUITE_NAME` params

### ISSUE THREAD

**Issue by tophat8855** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#22]
We need this variables for our drats to run and are not present in the integration config. Please add them back in. :)

**Comment by henryaj** [comment]
Hi @tophat8855 DEFAULT_TIMEOUT_MINS can be set with the `timeout` property on the integration config (which is now in milliseconds).

We have a story scheduled to implement the focus/skip functionality in the config here: https://www.pivotaltracker.com/story/show/152434450

**Comment by tinygrasshopper** [comment]
@tophat8855 we have changed the timeout field to be `timeout_in_minutes` in the integration config.

**Comment by selzoc** [comment]
@henryaj @tinygrasshopper Thanks for the update!  We'll be blocked from consuming the integration config task until we can skip a suite.  I've added that story as a blocker to ours.

**Comment by gcapizzi** [comment]
@tophat8855 @selzoc we have now added support for flags for individual testcases so everything requested in this issue should now be delivered.
