### ISSUE TITLE
DRATs fails with cf-cli 6.32.0

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#3]
This is a fun one. We were unable to get DRATs to run successfully using cf-cli 6.32.0, but it passes using cf-cli 6.31.0. The tests fail with the following error:

```
Creating org acceptance-test-org-CJ3Wj-z3vJwlkoMq1CdPsw as admin...
Polling url test-app-opufssk-9km-dxfzgeejuw.dour-fancier.capi.land
OK
Done polling url test-app-opufssk-9km-dxfzgeejuw.dour-fancier.capi.land

Assigning role OrgManager to user admin in org acceptance-test-org-CJ3Wj-z3vJwlkoMq1CdPsw ...
Polling url test-app-opufssk-9km-dxfzgeejuw.dour-fancier.capi.land
Done polling url test-app-opufssk-9km-dxfzgeejuw.dour-fancier.capi.land
OK

TIP: Use 'cf target -o "acceptance-test-org-CJ3Wj-z3vJwlkoMq1CdPsw"' to target new org
FAILED
```

However, if you comment out one of the test cases (either `NewCfAppTestCase` or `NewAppUptimeTestCase`) it passes even with the latest CLI. What we *think* is happening is the latest CLI changed the ordering of when the config file is written to disk and running [cf orgs](https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/blob/77891b96a00f2cc968a21b3045264a268292517b/testcases/uptime_testcase.go#L77) in the background while the second test case is running seems to be hitting a race condition where the CLI config file is getting overridden.

The CLI says that running multiple `cf` commands in parallel is not support but you can ask the CLI team for more info. Maybe a quick fix is to curl the root endpoint of the CC API to see whether CC is down rather than using the cf cli.

**Comment by flangewad** [comment]
Oooh, interesting. Thanks for the detailed issue :)

We have implemented the fix you suggested, and it's successfully made it through our pipelines with the updated `cf cli`.

So if you take the most recent DRATS from this repo you shouldn't see that problem again.

Thanks!
Rosie and Henry

**Comment by tinygrasshopper** [comment]
@ljfranklin this should be fixed in the latest version of DRATS, feel free to reopen if it does not work for you
