### ISSUE TITLE
Is there a way to run Drats against a cf deployment with windows cell?

### ISSUE THREAD

**Issue by Kaixiang** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#31]
Hi:

When we run drats test against a cf-deployment setup with windows cell enabled, we see errors like 
```
failed to find instances for deployment cf: couldn't find jobs: finding scripts failed on windows2016-cell/0bca09ab-c6ae-4f7e-b9e2-156b41a7f0a9: 'sudo' is not recognized as an internal or external command,
```

Is there a way to exclude windows cell? what is the right approach running it?
With many thanks.

**Comment by jamesjoshuahill** [comment]
Related issue: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/issues/15

**Comment by jamesjoshuahill** [comment]
Hi @Kaixiang 

Currently, cf-deployment with windows cells is not supported by bbr. And there is no way to skip an instance in the deployment when running `bbr deployment backup/restore`.

Best wishes
Josh and @alamages

**Comment by alamages** [comment]
Hello @Kaixiang 

We have a new [1.2.4 BBR](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/tag/v1.2.4) which works with windows VMs (it properly skips them without failing).

**Comment by Kaixiang** [comment]
Good to know, Thanks!
