### ISSUE TITLE
DRATs cannot run against a credhub-enabled environment

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#4]
It looks like DRATs expects to pull the CF admin password from the deployment manifest. This doesn't work in credhub-enabled envs as the manifest only contains references to the password (`((cf_admin_password))`).

We are currently using a fork of DRATs that takes in `CF_ADMIN_PASSWORD` as an env variable instead. This will break the DRATs flow of backing up from one env and restoring to another unless they both have the same admin password.

**Comment by tinygrasshopper** [comment]
@ljfranklin thanks for letting us know, we were aware of this issue, the fix is in flight in https://www.pivotaltracker.com/story/show/151244808, we have chosen a similar approach of taking in the cf creds from the ENV

**Comment by tinygrasshopper** [comment]
done with https://www.pivotaltracker.com/n/projects/1662777/stories/151244808
