### ISSUE TITLE
Failure leaves credhub in dirty state

### ISSUE THREAD

**Issue by pivotaljohn** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#41]
We had a drats failure in an `AfterBackup` which caused the tests to exit.

When trying to re-run the tests, we continually get this error:
```
  Expected
      <[]struct { Name string } | len:2, cap:4>: [
          {
              Name: "/SECRET_PASSWORD/2",
          },
          {
              Name: "/SECRET_PASSWORD/1",
          },
      ]
  to have length 1

  /tmp/build/f353ecef/src/github.com/pivotal-cf/pivotal-disaster-recovery-acceptance-tests/vendor/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/testcases/credhub_instance_creds_testcase.go:67
```

This seems to be because in the first test run, the `credhub_instance_creds_testcase.go` ran the `AfterBackup` and created a second value in credhub. When the tests were run again, the `BeforeBackup` fails when verifying that only a single entry exists in credhub.

It might be better to have a clean-up of the credhub key at the start of the test to ensure a known starting state.

This is on an older commit of the drats: `f73d02f32df7ffa6d9c95c64d8a08d480c6ede8d`, but it seems like the problem still exists.

cc @jpalermo @cloudfoundry-incubator/pcf-release-engineering

**Comment by MirahImage** [comment]
We have written to the credhub team and asked them to fix their test case by properly cleaning up in the Cleanup() step. 

Thank you for finding this issue. 

Best,
Mirah and @gmrodgers

**Comment by MirahImage** [comment]
Hi, 

We have merged a [PR from the CredHub team](https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/pull/37) which fixes this issue. 

Best,
Mirah and @alamages
