### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by ameowlia** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#50]
Hello, 

We, the networking program, run drats  in our pipeline and we noticed that we keep getting one flaky test. 

```
• Failure [1607.847 seconds]
backing up Cloud Foundry
/tmp/build/b7784222/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/acceptance/acceptance_test.go:12
  backups and restores a cf [It]
  /tmp/build/b7784222/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner/runner.go:52

  Timed out after 1200.000s.
  Command timed out: bbr deployment restore
  Expected process to exit.  It did not.

  /tmp/build/b7784222/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner/command_line_helpers.go:65

  Full Stack Trace
  	/tmp/build/b7784222/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:147 +0x403
  github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/vendor/github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).Should(0xc000200340, 0x8af620, 0xc00039a8e0, 0xc0001fe610, 0x1, 0x1, 0x29)
  	/tmp/build/b7784222/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:48 +0x62
  github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner.runCommandWithStream(0x845f7e, 0x16, 0x8ab860, 0xc00008ade0, 0x8ab860, 0xc00008ade0, 0xc0001dc1a0, 0x186, 0x0, 0x0, ...)
  	/tmp/build/b7784222/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner/command_line_helpers.go:65 +0x3a5
  github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner.RunCommandSuccessfullyWithFailureMessage(0x845f7e, 0x16, 0xc0001dc1a0, 0x186, 0x0, 0x0, 0x0, 0xc000024780)
  	/tmp/build/b7784222/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner/command_line_helpers.go:31 +0xbe
  github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner.RunDisasterRecoveryAcceptanceTests.func2()
  	/tmp/build/b7784222/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/runner/runner.go:120 +0xaad
  github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc00001e8a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/tmp/build/b7784222/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/acceptance/acceptance_suite_test.go:12 +0x63
  testing.tRunner(0xc000134900, 0x85c598)
  	/usr/local/go/src/testing/testing.go:827 +0xbf
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:878 +0x35c
```

All of the flakes are identical. And we've gotten it on approximately 20% of the runs on this environment. However, we have another pipeline that runs drats on different env, which has never seen this flake.

## Suspected Problem 
- [It looks like this test is failing](https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/blob/master/runner/runner.go#L120-L135)
- [Which calls this method]( https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/blob/master/runner/command_line_helpers.go#L30-L34)
- [Which results in a timeout here](https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/blob/master/runner/command_line_helpers.go#L65)

## Request 
The environment that we are running it on is a very large, so maybe it need more than 1200s to backup and restore? We were wondering where the 1200s is coming from? Is there a way that we can override it with something larger?

## Tagging other team members 
@bruce-ricard

if slack is better, feel free to reach out to us in `#networking` in the cf slack.

**Comment by jamesjoshuahill** [comment]
Hi @ameowlia 

What are the last lines of output from the `bbr deployment restore` command? If there is no sign of an error, then it may be an early timeout. The default timeout is 15 minutes (900 seconds). When you run DRATS the timeout must be configured to 20 minutes (1,200 seconds).

If you are using environment variables then it can be configured using `DEFAULT_TIMEOUT_MINS`, see https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/blob/63c244cc45a0fc6fad73feba4c6a587a6b939055/ci/drats/task.yml#L28.

If you are using integration config then it can be configured using `timeout_in_minutes`, see https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests/blob/63c244cc45a0fc6fad73feba4c6a587a6b939055/ci/integration_config.json#L26.

In our CI where we run all the test cases we use a 30 minute timeout. Please let us know if this resolves your problem.

Best wishes
Josh

**Comment by ameowlia** [comment]
Thanks @jamesjoshuahill! Trying this now!
